---
- name: install 
  become: yes
  apt: name=nginx state=latest
- name: start 
  become: yes
  service: name=nginx state=started enabled=true
- name: supprimer default config 
  become: yes
  file: path=/etc/nginx/sites-enalbled/default state=absent 
  notify: reload nginx
- name: configuration sites
  include: site.yml  
